services:
  - type: web
    name: forgex
    runtime: docker
    plan: free
    healthCheckPath: /
    envVars:
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: "3306"
      - key: DB_NAME
        value: ForgeX
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
